[package]
name = "ognlib"
version = "0.6.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Some code that is written to practice Rust"
authors = ["Maksim Bondarenkov"]
repository = "https://github.com/ognevnydemon/ognlib"
readme = "README.md"
rust-version = "1.67.1"

[dependencies]
num-bigint = { version = "0", optional = true }
rayon = { version = "1", optional = true }
thiserror = { version = "1", optional = true }

[dependencies.rand]
version = "0"
default-features = false
features = ["std", "std_rng"]
optional = true

[dependencies.regex]
version = "1"
default-features = false
features = ["std"]
optional = true

[features]
default = ["std"]
std = ["regex", "rayon", "rand", "thiserror", "num-bigint"]

[profile.testing]
debug = true
debug-assertions = true
incremental = false
inherits = "release"
lto = false
overflow-checks = true
strip = false
