[package]
name = "ognlib"
version = "0.5.15"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Some code that is written to practice Rust"
authors = ["Maksim Bondarenkov"]
repository = "https://github.com/ognevnydemon/ognlib"
readme = "README.md"
rust-version = "1.67.0"

[dependencies]
num-bigint = { version = "0", optional = true }
rayon = "1"
thiserror = "1"

[dependencies.rand]
version = "0"
default-features = false
features = ["std", "std_rng"]

[dependencies.regex]
version = "1"
default-features = false
features = ["std"]

[features]
default = ["num-bigint"]
num-bigint = ["dep:num-bigint"]

[profile.testing]
debug = true
debug-assertions = true
incremental = false
inherits = "release"
lto = false
overflow-checks = true
strip = false
