[package]
name = "ognlib"
version = "0.5.9"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Some code that is written to practice Rust"
authors = ["Maksim Bondarenkov"]
repository = "https://github.com/ognevnydemon/ognlib"
readme = "README.md"
rust-version = "1.65.0"

[dependencies]
rayon = "1.8"
num-bigint = "0.4"
regex = "1.10"
thiserror = "1"

[dependencies.rand]
version = "0.8"
default-features = false
features = ["std", "std_rng"]

[profile.testing]
inherits = "release"
debug = true
debug-assertions = true
overflow-checks = true
strip = false
lto = false
