[package]
name = "ognlib"
version = "0.4.8"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Some code that is written to practice Rust"
authors = ["Maksim Bondarenkov"]
repository = "https://github.com/ognevnydemon/ognlib"
readme = "README.md"
rust-version = "1.65.0"

[dependencies]
rayon = "1.7"

[dependencies.rand]
version = "0.8"
default-features = false
features = ["std", "std_rng"]

[dependencies.rug]
version = "1.22"
default-features = false
features = ["integer"]
