[package]
name = "ognlib"
version = "0.4.4"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Some code that is written to practice Rust"
authors = ["Maksim Bondarenkov"]
repository = "https://github.com/ognevnydemon/ognlib"
readme = "README.md"
rust-version = "1.59.0"

[dependencies]
rayon = "1.7"
num-bigint = "0.4"
rand = "0.8"
