[package]
name = "ognlib"
version = "0.5.11"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Some code that is written to practice Rust"
authors = ["Maksim Bondarenkov"]
repository = "https://github.com/ognevnydemon/ognlib"
readme = "README.md"
rust-version = "1.65.0"

[dependencies]
rayon = "1"
num-bigint = { version = "0", optional = true }
thiserror = "1"

[dependencies.rand]
version = "0"
default-features = false
features = ["std", "std_rng"]

[dependencies.regex]
version = "1"
default-features = false
features = ["std"]

[features]
default = ["num-bigint"]
num-bigint = ["dep:num-bigint"]

[profile.testing]
inherits = "release"
incremental = false
debug = true
debug-assertions = true
overflow-checks = true
strip = false
lto = false
