name: CI-nightly

on:
  push:
    paths: ["**.rs", "**.toml", "**/ci.yml", "**/nightly.yml"]
  pull_request:
    paths: ["**.rs", "**.toml", "**/ci.yml", "**/nightly.yml"]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-C target-cpu=native -Zmacro-backtrace -Zthreads=3"

jobs:
  lint:
    name: lint code using nightly
    runs-on: macos-15
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: default to rust nightly
        run: |
          rustup update nightly && rustup default nightly
          rustup component add rustfmt clippy
      - name: build
        run: cargo b -v
      - name: test
        run: cargo t -v
      - name: fmt and clippy check
        run: |
          cargo fmt -- --check
          cargo clippy
