name: CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: build using latest rust
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v3
      - name: update to ${{ matrix.toolchain }} rust
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - name: build using ${{ matrix.toolchain }} rust
        run: cargo b -v
      - name: test using ${{ matrix.toolchain }} rust
        run: cargo t -v
